######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Galaxy, Index = 0, Count = null
# SUBMIT FILE NAME : clean_up_local_level_5_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=2c83cfbb-b4e9-4da7-912a-5f5befd74499 PEGASUS_WF_LABEL=Galaxy PEGASUS_DAG_JOB_ID=clean_up_local_level_5_0 PEGASUS_SITE=local"
arguments = " -n pegasus::cleanup -N null -i - -R local  -L Galaxy -T 2021-04-08T19:14:50+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-transfer "
error = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001//00/00/clean_up_local_level_5_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
input = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001//00/00/clean_up_local_level_5_0.in
log = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001/Galaxy-0.log
notification = NEVER
output = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001//00/00/clean_up_local_level_5_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "2c83cfbb-b4e9-4da7-912a-5f5befd74499"
+pegasus_wf_uuid = "2c83cfbb-b4e9-4da7-912a-5f5befd74499"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Galaxy-0"
+pegasus_wf_time = "20210408T191451+0000"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "clean_up_local_level_5_0"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
