######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Galaxy, Index = 0, Count = null
# SUBMIT FILE NAME : Test_Preprocess_py_ID0000005.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=2c83cfbb-b4e9-4da7-912a-5f5befd74499 PEGASUS_WF_LABEL=Galaxy PEGASUS_DAG_JOB_ID=Test_Preprocess_py_ID0000005 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001//00/00/Test_Preprocess_py_ID0000005.err
executable = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001/00/00/Test_Preprocess_py_ID0000005.sh
initialdir = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/wf-scratch/LOCAL/scitech/pegasus/Galaxy/run0001
log = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001/Galaxy-0.log
notification = NEVER
output = /home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001//00/00/Test_Preprocess_py_ID0000005.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = Class0_3.jpg,Class1_4.jpg,Class4_4.jpg,Class3_4.jpg,Test_Preprocess_py,Class2_2.jpg,/home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001/00/00/Data_Labeling_py_py_ID0000001.meta,/home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001/00/00/stage_in_local_local_1_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/Galaxy2/galaxy-image-classification/scitech/pegasus/Galaxy/run0001/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = Test_images_Preprocess.npy,Test_labels_Preprocess.npy
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "2c83cfbb-b4e9-4da7-912a-5f5befd74499"
+pegasus_wf_uuid = "2c83cfbb-b4e9-4da7-912a-5f5befd74499"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Galaxy-0"
+pegasus_wf_time = "20210408T191451+0000"
+pegasus_wf_xformation = "Test_Preprocess.py"
+pegasus_wf_dax_job_id = "ID0000005"
+pegasus_wf_dag_job_id = "Test_Preprocess_py_ID0000005"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
